### ISSUE TITLE
Drain cleaner pod seems to be stuck

### ISSUE THREAD

**Issue by OuesFa** [strimzi/drain-cleaner#58] opened 2022-09-26 11:12 UTC
Hello 👋 

Using drain cleaner 0.3.0

From time to time, the strimzi drain cleaner pod gets stuck. 

By stuck I mean that there are no more logs printed as it usually does, and we detect many eviction attempts on the strimzi pods while the drain cleaner is not responding. 

This is not a configuration issue because after the pod restarts, the drain cleaner is able to intercept the eviction webhook and correctly annotate the strimzi kafka or zookeeper pod related to the eviction attempt. 
It is not a resource problem either, as the memory and cpu request is much higher than the container usage.

This is very important for us, because GKE will force the pod to be deleted after an hour of time, even if pdb maxUnavailable is set to 0.

Does this sound familiar? 
How can I investigate further? More debug level or check something in particular. I'm not sure what to do either.

**Comment by scholzj** [comment] 2022-09-26 11:51
Did you checked Kubernetes logs? Do you know if it actually passes the eviction requests and what the result it? Also, it is always wroth trying to upgrade to the latest version with the updated dependencies etc.

**Comment by OuesFa** [comment] 2022-09-26 13:13
> it is always wroth trying to upgrade to the latest version

I'm updating to 0.3.1 👍 

> Did you checked Kubernetes logs? 

I checked the drain cleaner pod logs indeed, there was none, since several hours. Sometime several days (if the pod is not evicted)

> Do you know if it actually passes the eviction requests and what the result it?

I can see the eviction attempts failing in the GCP console, logs like this 

```json
{
  "protoPayload": {
    ...
    "methodName": "io.k8s.core.v1.pods.eviction.create",
    "request": {
      "@type": "policy.k8s.io/v1beta1.Eviction",
      "apiVersion": "policy/v1beta1",
      "deleteOptions": {
        "gracePeriodSeconds": 150
      },
      "kind": "Eviction",
      "metadata": {
        "creationTimestamp": null,
        "name": "platform-kafka-kafka-2",
        "namespace": "platform"
      }
    },
    "resourceName": "core/v1/namespaces/platform/pods/platform-kafka-kafka-2/eviction",
    "response": {
      "@type": "core.k8s.io/v1.Status",
      "apiVersion": "v1",
      "code": 429,
      "details": {
        "causes": [
          {
            "message": "The disruption budget platform-kafka-kafka needs 3 healthy pods and has 3 currently",
            "reason": "DisruptionBudget"
          }
        ]
      },
      "message": "Cannot evict pod as it would violate the pod's disruption budget.",
  },
    ...
  "receiveTimestamp": "2022-09-26T09:58:52.756406739Z"
}
```

When I restart the drain cleaner the logs resume, I can see the drain cleaner intercepting the eviction webhook and annotating the involved strimzi pod, and the GCP logs like the one above stop being sent => normal behaviour. 

Also, out of curiosity, why is the drain cleaner not implemented as part of the cluster operator itself, it seems to be appropriate for the cluster operator to be able (if enabled via config) to watch eviction webhooks on its own resources and annotate them accordingly?

**Comment by scholzj** [comment] 2022-09-26 13:18
> I checked the drain cleaner pod logs indeed, there was none, since several hours. Sometime several days (if the pod is not evicted)

Sure, but it normally doesn't log anything unless Kubernetes send a request to it. So I think you should check the Kubernetes logs, if Kubernetes is forwarding the Eviction requests to it and what response it is getting. You can also try to send it some eviction request manually to see it works. Because IIRC, if it doesn't get any requests, it will not log anything.

**Comment by scholzj** [comment] 2022-09-26 13:22
> Also, out of curiosity, why is the drain cleaner not implemented as part of the cluster operator itself, it seems to be appropriate for the cluster operator to be able (if enabled via config) to watch eviction webhooks on its own resources and annotate them accordingly?

First, because not everyone cares about this. Also, the installation of webhooks is complicated and they don't always follow the same scope as the operator does.

**Comment by OuesFa** [comment] 2022-09-27 11:58
> So I think you should check the Kubernetes logs, if Kubernetes is forwarding the Eviction requests to it and what response it is getting.

Is it not the log (in json) I've put above? Indicating that `Cannot evict pod as it would violate the pod's disruption budget.`? 


> You can also try to send it some eviction request manually to see it works.

Thanks for the lead, I will test that next time it is stuck.

> First, because not everyone cares about this

I'm curious to know why some would not be interested in this feature? AFAIU it's the only way to avoid brokers being evicted and killed abruptly, right? In case it's not the operator that handles the restart via annotation, nobody makes sure that partitions are not under replicated or under isr min during the rollout right?

How do people ensure that the rollout (in case of eviction) goes smoothly other than via drain cleaner?

**Comment by scholzj** [comment] 2022-09-27 12:48
> Is it not the log (in json) I've put above? Indicating that Cannot evict pod as it would violate the pod's disruption budget.?

I don't know. JSON logs are confusing. What Kubernetes component is the log from? In any case, it does not say anything about calling a webhook and getting some result or error from the Drain Cleaner. That would be somewhere int he APi server or controller logs or something like that.

> I'm curious to know why some would not be interested in this feature? AFAIU it's the only way to avoid brokers being evicted and killed abruptly, right? In case it's not the operator that handles the restart via annotation, nobody makes sure that partitions are not under replicated or under isr min during the rollout right?
> How do people ensure that the rollout (in case of eviction) goes smoothly other than via drain cleaner?

The Drain Cleaner makes sure the Kafka cluster is available during the node draining, since the Operator checks the state of the different partition replicas during the rolling of the broker pods. Not everyone cares about that. For example, sometimes you do this when you are closed for business and you prioritize having the draining done quickly regardless the availability etc.

**Comment by OuesFa** [comment] 2022-09-27 13:00
> That would be somewhere int he APi server or controller logs or something like that.

Ok I will try to find that as well, thanks again for the leads 👍 

> since the Operator checks the state of the different partition replicas during the rolling of the broker pods.

I'm not sure to understand sorry 🙇‍♂️,  does this mean that, in case I `kubectl delete my-cluster-kafka-0` (I understand that this is basically what happens when kube evicts a pod) the cluster operator ensures the different partitions are well replicated? 

> Not everyone cares about that. For example, sometimes you do this when you are closed for business and you prioritize having the draining done quickly regardless the availability etc.

Ok I didn't think about that indeed 👍 
In my case it's pretty important, the clusters are meant to be available 24/7, and I'm having 3 brokers with  `RF=3` for all topics with `min.isr=2` and all producers with `acks=all` so every time a broker is in bad shape it's a bit dangerous.

**Comment by scholzj** [comment] 2022-09-27 13:10
> I'm not sure to understand sorry 🙇‍♂️, does this mean that, in case I kubectl delete my-cluster-kafka-0 (I understand that this is basically what happens when kube evicts a pod) the cluster operator ensures the different partitions are well replicated?

No, it does not. And this is what Kubernetes would normally do when evicting the pod if the Pod Disruption Budget would not prevent it. The combination of the Drain Cleaner and the Pod Disruption Budget does the following:
* The PDB would prevent Kubernetes from just deleting the pod such as `kubectl delete pod` would do
* The Drain Cleaner captures that Kubernetes are trying to evict the Pod through a webhook (this is what was either not called or what was not responded to)
* The Drain Cleaner will instruct the operator to _roll_ the pod
* The Cluster Operator will check the partition replicas, whether they are in sync and only if they are, it will delete the Pod

So that way, it ensures the availability.

**Comment by scholzj** [comment] 2022-09-27 13:53
[This](https://github.com/strimzi/drain-cleaner/blob/main/development-docs/TESTING.md#unit-tests) should help you with the second part. It shows how to send the requests to the Drain Cleaner ... you just need to use the right address since it will not be running locally in your case.

**Comment by OuesFa** [comment] 2022-09-27 20:45
Oh perfect that helps a lot!

As usual, thanks very much for your precious help 🙏

**Comment by mateusaueressig** [comment] 2022-11-15 16:10
Hi all!

I'm experiencing the exact same behavior. 

I checked the kubernetes api server logs and found out that the webhook was failing:
`E1111 09:08:24.777469      10 dispatcher.go:146] failed calling webhook "drain-cleaner.strimzi.io": Post "https://drain-cleaner.kafka.svc:443/drainer?timeout=5s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "drain-cleaner")`

Also, I saw in the cert-manager pod logs that the certificate had been renewed (because the existing certificate reached the renewal date) some days before the drain event, but the drain-cleaner pod was not restarted, so I am pretty sure the drain-cleaner pod is still using the old certificate and therefore the webhook fails to call it.

I'm using drain cleaner 0.3.1.

Steps to reproduce:
1. Install cert-manager
2. Install kubectl cert-manager plugin (https://cert-manager.io/v1.0-docs/usage/kubectl-plugin/)
3. Install drain-cleaner in the cert-manager mode with the strimzi suggested files (https://github.com/strimzi/drain-cleaner/tree/main/install/certmanager)
4. Initially drain-cleaner works
5. Manually trigger a renew of the certificate with: `kubectl cert-manager renew CERTIFICATE-NAME -n kafka`
6. Checked that all k8s objects were updated with the new certificate (Certificate.cert-manager.io, Secret with the certificate, validatingwebhookconfigurations.admissionregistration.k8s.io)
7. Trigger a node drain
8. Drain-cleaner logs remain still and an webhook error I mentioned above is seen in the kubernetes api server logs
9. Once I kill the drain-cleaner pod, the new restarted pod is triggered by the webhook with success.

Wouldn't it make sense that the drain-cleaner application has some logic to detect the new updated certificate? Or how would you suggest to solve this?

**Comment by scholzj** [comment] 2022-11-15 19:27
@mateusaueressig The Drain Cleaner needs to be restarted when the certificate is renewed. It does not restart itself currently. That might be a reasonable enhancement. But it is not really obvious how it relates to this issue where you commented. Why do you think it is the same issue?

**Comment by scholzj** [comment] 2022-12-01 20:27
Ok, so its not related to the issue which @mateusaueressig has after all.

----

So, what does Google do? Ignore the Pod Disruption Budget completely? Or just never scale down the node with such pod? I think the second option is kinda valid solution. The first one - just ignoring the PDB - would be quite weird. 

Either way, I do not think you have too many options. You can rely on the readiness only and risk that you will loose availability. Or you can take it as it is. To be honest, I would probably not schedule my Kafka cluster on nodes which are coming up and down through some autoscaler and I would prefer fixed nodes for it. But I do not know the details of your Kafka deployment.

**Comment by mateusaueressig** [comment] 2022-12-02 08:11
@scholzj true. But thanks a lot anyway for opening https://github.com/strimzi/drain-cleaner/pull/61!

In the meantime, as a workaround for my problem, I did the following:
- Instead of using just 1 Issuer/Certifiate as proposed in https://github.com/strimzi/drain-cleaner/tree/main/install/certmanager, I configured 2 Issuers/Certificates (root/leaf)
- Since the webhook is configured with the root certificate, when cert-manager renews the leaf certificate, there is a window where both old/new leaf certificate are valid: so drain-cleaner does not stop immediately to work
- Then I added a CronJob to restart drain-cleaner within this window

But your enhancement is very much welcome, as we won't need the CronJob anymore.

PS: thank you for developing and maintaining this great project that strimzi (drain-cleaner included) is!

**Comment by OuesFa** [comment] 2022-12-07 10:17
>So, what does Google do? Ignore the Pod Disruption Budget completely? Or just never scale down the node with such pod? I think the second option is kinda valid solution.
Yes, never scale down when maxUnavailable equals 0 (except in case of a gke upgrade where they force the deletion of the pod after an hour of waiting )

**Comment by scholzj** [comment] 2022-12-07 17:44
> Yes, never scale down when maxUnavailable equals 0 (except in case of a gke upgrade where they force the deletion of the pod after an hour of waiting )

Well, I guess such approach might not be against the spec. But it does not make it easier to integrate into it really scalable applications. But I guess there is not much to do to work around it. It is simply a limitation of GKE.

**Comment by scholzj** [comment] 2023-02-02 23:18
@mateusaueressig FYI: we released 0.4.0 which has the reloading which seems to work. I had to re-work it as the original solution did not work well, so it took more time. But not it should be available now.

@OuesFa Not really sure what to do with this issue. I don't think there is much we can do about it here. Should we close it?

**Comment by mateusaueressig** [comment] 2023-02-03 08:11
@scholzj that's awesome! Thank you so much!

**Comment by OuesFa** [comment] 2023-02-03 17:56
Let's close it indeed, thanks for your help on this!

**Closed** 2023-02-03 18:25 UTC
